


// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).



/// <reference path="\Coalesce\intellitect.ko.base.ts" />
/// <reference path="\Coalesce\intellitect.ko.bindings.ts" />
/// <reference path="\Coalesce\intellitect.ko.utilities.ts" />
/// <reference path="\Coalesce\intellitect.utilities.ts" />
/// <reference path="Generated\Ko.ApplicationUser.ts" />
/// <reference path="Generated\Ko.ApplicationUserList.ts" />
