


// This file is automatically generated.
// It is not in the generated folder for ease-of-use (no relative paths).



/// <reference path="coalesce.dependencies.d.ts" />
/// <reference path="Generated\Ko.ApplicationUser.ts" />
/// <reference path="Generated\Ko.ApplicationUserList.ts" />
